"""Add user activity tracking fields

Revision ID: 8f51098dbb7b
Revises: dcfe53ad4ab4
Create Date: 2025-10-02 02:05:31.678719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f51098dbb7b'
down_revision = 'dcfe53ad4ab4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bot_started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('app_opened_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('app_opened_count', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('last_app_opened_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_app_opened_at')
    op.drop_column('users', 'app_opened_count')
    op.drop_column('users', 'app_opened_at')
    op.drop_column('users', 'bot_started_at')
    # ### end Alembic commands ###
