"""Fix question fields and survey question_count

Revision ID: ad7057b24df0
Revises: 8f51098dbb7b
Create Date: 2025-10-02 13:52:20.837135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad7057b24df0'
down_revision = '8f51098dbb7b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('surveys', 'question_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('surveys', 'question_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
